// ════════════════════════════════════════════════════════════════════════
//  yourZ — THE STAGE LIBRARY. Wide by law (roadmap §4): every scene has a
//  MISSION — an objective and a judged verdict. Global English register.
//  Fictionalization law: real situations, never named living people; both
//  sides at their fair strongest (triply so in geopolitics & headlines).
//  desc = the premise WITH your role and objective — it is sent to the
//  moderator as the brief, so the library is client-side and infinite.
// ════════════════════════════════════════════════════════════════════════

export const GENRES = [
  { id: 'geo',    label: 'geopolitics',            note: 'the envoy, never a named leader' },
  { id: 'court',  label: 'crime & courtroom',      note: '' },
  { id: 'spy',    label: 'espionage',              note: '' },
  { id: 'myst',   label: 'mystery',                note: 'the moderator commits the truth at the opening' },
  { id: 'surv',   label: 'survival',               note: '' },
  { id: 'corp',   label: 'boardrooms & startups',  note: '' },
  { id: 'heist',  label: 'heists & cons',          note: '' },
  { id: 'hist',   label: 'history-inspired',       note: '' },
  { id: 'heart',  label: 'reckonings',             note: '' },
  { id: 'spec',   label: 'other worlds',           note: '' },
  { id: 'light',  label: 'lighter stakes',         note: '' },
];

export const LIBRARY = [
  // ── geopolitics — the flagship genre ──
  { id: 'ceasefire',  g: 'geo', name: 'The Ceasefire',      ic: '☮', tag: 'brinkmanship', desc: "two nations, five days of shelling, one night to stop it. you're the neutral envoy at the midnight table — both delegations want to walk. keep them in the room and get a signature.", cast: ['the_leader_opp','the_orator','the_cynic','the_economist'] },
  { id: 'watertreaty',g: 'geo', name: 'The River',          ic: '〜', tag: 'resource crisis', desc: "the river feeds two countries and the upstream dam is closing. you represent the downstream nation — no treaty by dawn means the farms die. negotiate water for a proud neighbor's price.", cast: ['the_economist','the_leader_opp','the_cynic','the_historian'] },
  { id: 'summit',     g: 'geo', name: "The Envoy's Summit", ic: '◈', tag: 'superpowers', desc: "you're the smaller nation's envoy seated between two superpowers carving up your region's future. neither takes you seriously. leave with your country's interests intact.", cast: ['the_leader_opp','the_orator','the_media_manager','the_cynic'] },
  { id: 'sanctions',  g: 'geo', name: 'The Vote',           ic: '⚖', tag: 'security council', desc: "a sanctions vote at dawn, one swing delegation undecided — yours to flip. their price is something your government swore never to give. find the third option.", cast: ['the_leader_opp','the_economist','the_orator'] },
  { id: 'exchange',   g: 'geo', name: 'The Bridge',         ic: '⇋', tag: 'prisoner exchange', desc: "a fog-bound bridge at 4am, three prisoners on each side, and intelligence says one of theirs is not who they claim. you run the exchange. everyone comes home — or no one does.", cast: ['the_cynic','the_leader_opp','the_oracle','the_brother'] },
  { id: 'hotline',    g: 'geo', name: 'The Hotline',        ic: '☎', tag: 'de-escalation', desc: "a radar glitch, a scrambled squadron, twenty minutes before someone acts on bad information. you're the duty officer on the direct line to the other side. talk both capitals down.", cast: ['the_leader_opp','the_cynic','the_brainiac'] },
  { id: 'embargo',    g: 'geo', name: 'The Port',           ic: '⚓', tag: 'trade war', desc: "your country's grain ships are locked out of the strait and winter is coming. across the table: the minister who ordered it, enjoying the leverage. reopen the port without giving up the coastline rights.", cast: ['the_economist','the_leader_opp','the_media_manager'] },
  { id: 'asylum',     g: 'geo', name: 'The Terminal',       ic: '✈', tag: 'asylum standoff', desc: "a scientist from a hostile state walks into your embassy's airport lounge asking for asylum — carrying something that isn't theirs. grant it and trigger a crisis; refuse and sign their fate. decide, and defend it.", cast: ['the_cynic','the_leader_opp','the_healer','the_oracle'] },
  // ── crime & courtroom ──
  { id: 'courtroom',  g: 'court', name: 'The Verdict',      ic: '⚖', tag: 'murder trial', desc: "closing arguments in a murder trial the whole country's watching. you're the defense — the evidence is bad, the jury's hostile. make them doubt.", cast: ['the_orator','the_leader_opp','the_cynic','the_brother'] },
  { id: 'crossexam',  g: 'court', name: 'The Witness',      ic: '⚖', tag: 'legal thriller', desc: "a hostile witness who knows more than they're saying. ten questions to break their story before the judge cuts you off.", cast: ['the_leader_opp','the_cynic','the_orator'] },
  { id: 'interrogation', g: 'court', name: 'The Interrogation', ic: '⚖', tag: 'crime', desc: "a suspect across a steel table, a lawyer on the way, the truth somewhere in between. crack them before the clock runs out — or play the suspect and hold.", cast: ['the_cynic','the_leader_opp','the_wingman'] },
  { id: 'juryroom',   g: 'court', name: 'The Twelfth Chair', ic: '▣', tag: 'jury room', desc: "eleven jurors ready to convict tonight and go home. you're the holdout — something in the timeline doesn't fit. turn the room, one juror at a time.", cast: ['the_cynic','the_brother','the_diva','the_economist'] },
  { id: 'parole',     g: 'court', name: 'The Hearing Room', ic: '◫', tag: 'parole board', desc: "twenty years served, a model record, a victim's family in the second row. you make the case for release — or play the board member who must decide. someone leaves this room changed.", cast: ['the_healer','the_cynic','the_leader_opp'] },
  { id: 'guilty',     g: 'court', name: 'The Client',       ic: '✉', tag: 'ethics', desc: "your client just told you, privately, that they did it — and the trial starts monday. defend them within the law's lines, or find the door out. the bar is watching either way.", cast: ['the_philosopher','the_cynic','the_leader_opp'] },
  { id: 'appeal',     g: 'court', name: 'The Last Appeal',  ic: '⚖', tag: 'innocence', desc: "new evidence, an old conviction, a court that hates reopening anything. you have one hearing to get an innocent person's case heard. the clock on their sentence is real.", cast: ['the_orator','the_leader_opp','the_cynic','the_healer'] },
  // ── espionage ──
  { id: 'defector',   g: 'spy', name: 'The Defector',       ic: '✆', tag: 'midnight meet', desc: "a midnight meet in a foreign city. the asset wants out, the handler smells a trap, one of you is being followed. get the truth and get clear.", cast: ['the_cynic','the_leader_opp','the_oracle','the_media_manager'] },
  { id: 'mole',       g: 'spy', name: 'The Mole',           ic: '✆', tag: 'traitor inside', desc: "a leak inside the agency and the evidence points at you. one room, four colleagues, one real traitor. clear your name or expose them.", cast: ['the_leader_opp','the_cynic','the_self_obsessed','the_brother'] },
  { id: 'deaddrop',   g: 'spy', name: 'The Drop',           ic: '◉', tag: 'gone wrong', desc: "the dead drop was compromised and your contact missed two windows. now a stranger sits on the park bench holding the right newspaper wrong. walk away with the package — or with your cover.", cast: ['the_cynic','the_stranger','the_oracle'] },
  { id: 'double',     g: 'spy', name: 'The Double',         ic: '⧉', tag: 'handler', desc: "you run a double agent who just fed you something too good to be true. across a café table, decide: is your best source turned, or about to hand you the win of the decade?", cast: ['the_cynic','the_diva','the_leader_opp'] },
  { id: 'extraction', g: 'spy', name: 'The Extraction',     ic: '⇱', tag: 'no clean exit', desc: "your agent's cover collapses at a state dinner in a hostile capital. three exits, two watched, one hour. get them out through conversation, cover, and nerve.", cast: ['the_wingman','the_cynic','the_media_manager','the_diva'] },
  // ── mystery (hidden-commitment scenes) ──
  { id: 'whodunit',   g: 'myst', name: 'The Locked Room',   ic: '☖', tag: 'whodunit', desc: "a body, a storm, five suspects, no way in or out. you're the detective. one of them is lying to your face. find the killer before morning.", cast: ['the_cynic','the_philosopher','the_crush','the_brother','the_self_obsessed'] },
  { id: 'reunion',    g: 'myst', name: 'The Reunion',       ic: '✦', tag: 'old friends', desc: "ten years since college, one weekend villa, and by midnight the host is dead at the bottom of the stairs. everyone here loved them once. you knew them best — find what happened before the police arrive.", cast: ['the_crush','the_cynic','the_comic','the_diva'] },
  { id: 'forgery',    g: 'myst', name: 'The Forgery',       ic: '❖', tag: 'art world', desc: "the masterpiece that anchors tomorrow's auction is a fake — you're the authenticator who spotted it, and someone in this gallery swapped it. name the hand before the hammer falls.", cast: ['the_diva','the_cynic','the_historian','the_media_manager'] },
  { id: 'gala',       g: 'myst', name: 'The Toast',         ic: '☾', tag: 'poisoning', desc: "a billionaire collapses mid-toast at their own gala. the glass was poisoned, the doors are sealed, and the heirs are already lawyering. you have until the ambulance arrives to find who raised the fatal glass.", cast: ['the_cynic','the_diva','the_economist','the_wingman'] },
  // ── survival ──
  { id: 'lifeboat',   g: 'surv', name: 'The Lifeboat',      ic: '⚟', tag: 'open water', desc: "too many people, not enough water, land days away. tempers fracture, a leader is needed, and someone has to make the call no one wants to. it's you.", cast: ['the_cynic','the_healer','the_brother','the_self_obsessed'] },
  { id: 'summit_climb', g: 'surv', name: 'The Last Ascent', ic: '⛰', tag: 'the mountain', desc: "a storm closing on the mountain, a hurt climber, a choice between the summit you bled for and getting everyone home. the team's looking at you.", cast: ['the_brother','the_cynic','the_healer','the_mentor'] },
  { id: 'bunker',     g: 'surv', name: 'The Shelter',       ic: '▦', tag: 'who gets in', desc: "the shelter holds eight. eleven people stand at the door as the sirens start. you hold the list and the latch. decide, out loud, with everyone listening.", cast: ['the_philosopher','the_healer','the_cynic','the_self_obsessed'] },
  { id: 'wildfire',   g: 'surv', name: 'The Ridge',         ic: '♨', tag: 'evacuation', desc: "the fire jumped the ridge an hour early and one road out is already smoke. you're the volunteer captain of a town that doesn't want to leave. move three hundred stubborn people before midnight.", cast: ['the_brother','the_cynic','the_mentor','the_healer'] },
  { id: 'convoy',     g: 'surv', name: 'The Convoy',        ic: '☀', tag: 'the desert', desc: "two trucks, one working radio, a wrong turn eighty kilometres deep in the dunes. water for two days. the group wants to split up — history says that kills everyone. hold them together and find the road.", cast: ['the_cynic','the_brother','the_oracle'] },
  // ── boardrooms & startups ──
  { id: 'interview',  g: 'corp', name: 'The Interview',     ic: '◉', tag: 'final round', desc: "the final round for the job that changes everything. three interviewers, one impossible panel, every answer a test. land it.", cast: ['the_leader_opp','the_economist','the_cynic'] },
  { id: 'pitch',      g: 'corp', name: 'The Pitch',         ic: '◉', tag: 'the investors', desc: "sixty seconds with the investors who could make you — or end you. they're bored and they've heard it all. make them believe.", cast: ['the_economist','the_cynic','the_wannabe','the_media_manager'] },
  { id: 'raise',      g: 'corp', name: 'The Ask',           ic: '◉', tag: 'negotiation', desc: "you've earned the raise. they're hoping you won't push. one conversation, a boss who deflects, your whole worth on the line. don't fold.", cast: ['the_economist','the_leader_opp','the_media_manager'] },
  { id: 'boardroom',  g: 'corp', name: 'The Coup',          ic: '◈', tag: 'the vote at dawn', desc: "the board's turned, the founder's cornered, the vote is at dawn. play the founder fighting to keep your company — or the one taking it.", cast: ['the_economist','the_leader_opp','the_media_manager','the_cynic'] },
  { id: 'acquisition',g: 'corp', name: 'The Number',        ic: '◈', tag: 'the exit', desc: "they want to buy your life's work and their first offer is an insult designed to anchor you low. across the table: their smiling M&A shark. get your number — or walk with the company intact.", cast: ['the_economist','the_diva','the_cynic'] },
  { id: 'whistle',    g: 'corp', name: 'The File',          ic: '⚑', tag: 'whistleblower', desc: "you found the fraud. it's real, it's big, and it implicates the person who mentored you. the journalist is waiting, legal is circling, and your career is the ante. decide what the truth is worth.", cast: ['the_cynic','the_media_manager','the_mentor','the_healer'] },
  // ── heists & cons ──
  { id: 'heist',      g: 'heist', name: 'The Last Job',     ic: '◈', tag: 'the vault', desc: "the crew, the vault, one shot. something's already gone wrong and someone at this table is lying. you're running it. hold the plan together.", cast: ['the_wingman','the_cynic','the_brother','the_self_obsessed'] },
  { id: 'thecon',     g: 'heist', name: 'The Long Game',    ic: '♠', tag: 'the con', desc: "six weeks building the perfect con and tonight the mark finally sits across from you — except they're sharper than the file said, and they're running their own angle. out-play a player.", cast: ['the_diva','the_cynic','the_wingman'] },
  { id: 'museum',     g: 'heist', name: 'The Gallery Job',  ic: '❖', tag: 'planning table', desc: "the museum's crown piece, a fifteen-minute guard gap, and a crew that doesn't trust each other yet. you drew the plan. sell it to them, fix its one flaw, and pick who holds the keys.", cast: ['the_brainiac','the_wingman','the_cynic','the_comic'] },
  { id: 'getaway',    g: 'heist', name: 'The Morning After', ic: '☕', tag: 'the alibi', desc: "the job went clean but the driver got picked up at dawn, and now a very polite detective is buying you coffee. every answer needs to be boring. survive the friendliest interrogation of your life.", cast: ['the_cynic','the_stranger','the_wingman'] },
  // ── history-inspired ──
  { id: 'mutiny',     g: 'hist', name: 'The Mutiny',        ic: '⚓', tag: 'the high seas', desc: "a ship far from home, a captain gone too far, a crew at the edge. lead the mutiny — or talk them back from it. the deck is watching.", cast: ['the_brother','the_cynic','the_leader_opp','the_orator'] },
  { id: 'trial_hist', g: 'hist', name: 'The Heretic',       ic: '✡', tag: 'dangerous truth', desc: "a great thinker on trial for a dangerous new truth, a council that wants them silenced. defend the idea that could change the world — or recant to live.", cast: ['the_philosopher','the_leader_opp','the_guru','the_cynic'] },
  { id: 'throne',     g: 'hist', name: 'The Empty Throne',  ic: '♛', tag: 'succession', desc: "a dead emperor, no heir, a hall of ruthless lords. you're the underestimated outsider with only your wits.", cast: ['the_leader_opp','the_cynic','the_philosopher','the_brother'] },
  { id: 'siege',      g: 'hist', name: 'The Gates',         ic: '⛨', tag: 'the siege', desc: "the army camps outside the walls, the granaries hold six weeks, and the council is split between proud death and shameful terms. you hold the deciding voice. choose what the city becomes.", cast: ['the_leader_opp','the_healer','the_cynic','the_historian'] },
  { id: 'twocourts',  g: 'hist', name: 'The Marriage of Crowns', ic: '♚', tag: 'broker the peace', desc: "two kingdoms, a century of war, and one winter feast where both courts sit at your table. you're the go-between with no army — end the war with words, dowries, and nerve.", cast: ['the_historian','the_diva','the_leader_opp','the_orator'] },
  // ── reckonings ──
  { id: 'dinner',     g: 'heart', name: 'The Dinner',       ic: '♥', tag: 'meeting the parents', desc: "meeting their family for the first time. the father's cold, the mother's testing you, one wrong word sinks it. win the table.", cast: ['the_brother','the_cynic','the_healer','the_crush'] },
  { id: 'reconcile',  g: 'heart', name: 'The Last Visit',   ic: '❧', tag: 'reckoning', desc: "a hospital room, an estranged parent, not much time left, everything you both never said. some doors open once. walk through it.", cast: ['the_healer','the_brother','the_philosopher'] },
  { id: 'breakup',    g: 'heart', name: 'The Crossroads',   ic: '❧', tag: 'the conversation', desc: "the conversation you've both been avoiding for months. tonight it happens. say the true thing — fight for it, or let it go honestly.", cast: ['the_crush','the_healer','the_cynic'] },
  { id: 'ledge',      g: 'heart', name: 'The Ledge',        ic: '☎', tag: 'standoff', desc: "a hostage standoff. play the negotiator talking them down — or the desperate one looking for a way out.", cast: ['the_wingman','the_brother','the_healer'] },
  { id: 'objection',  g: 'heart', name: 'The Toastmaster',  ic: '♦', tag: 'the wedding', desc: "your best friend marries in twelve hours and last night you learned something the vows can't survive. the rehearsal dinner is now. speak, stay silent, or find the third way — and live with it.", cast: ['the_brother','the_healer','the_cynic','the_comic'] },
  { id: 'inheritance',g: 'heart', name: 'The Reading',      ic: '✉', tag: 'the will', desc: "the lawyer reads the will and the house goes to the sibling who left. the room is family, grief, and thirty years of scorekeeping. get what's fair without burning what's left.", cast: ['the_cynic','the_healer','the_diva','the_brother'] },
  // ── other worlds ──
  { id: 'firstcontact', g: 'spec', name: 'First Light',     ic: '✧', tag: 'first contact', desc: "the signal was real, the ship is in orbit, and the delegation of one sits across from you, learning our words fast. you speak for everyone. don't get us quarantined — or worse.", cast: ['the_cosmologist','the_philosopher','the_cynic','the_leader_opp'] },
  { id: 'android',    g: 'spec', name: 'The Personhood Hearing', ic: '◬', tag: 'is it alive', desc: "the machine asked for a lawyer, and the hearing that decides whether it's property or a person starts now. argue either side at full strength. the transcript will outlive everyone in the room.", cast: ['the_philosopher','the_brainiac','the_leader_opp','the_healer'] },
  { id: 'archive',    g: 'spec', name: 'The Archive',       ic: '⬡', tag: 'justify us', desc: "the last archive of a dying civilization can save exactly one culture's record — and its keeper interviews you tonight about whether humanity's is worth the space. make the case, flaws and all.", cast: ['the_philosopher','the_historian','the_cynic'] },
  { id: 'colonyvote', g: 'spec', name: 'The Long Ship',     ic: '✵', tag: 'generation ship', desc: "forty years out, a repairable engine, and a signal from earth that changes everything: come home, or burn for the new world. the ship votes at dawn — you speak last. carry the room.", cast: ['the_cosmologist','the_leader_opp','the_healer','the_brother'] },
  { id: 'dragon',     g: 'spec', name: 'The Parley',        ic: '☲', tag: 'high fantasy', desc: "the dragon has terms. the kingdom sent you — no sword, one satchel of gold, and a title it finds hilarious. negotiate with something older, richer, and smarter than your entire court.", cast: ['the_diva','the_philosopher','the_cynic'] },
  { id: 'timetrib',   g: 'spec', name: 'The Tribunal of Hours', ic: '⧗', tag: 'time travel', desc: "you changed one small thing a century back and the tribunal that polices the timeline wants it justified. the ripple saved someone you love and cost strangers plenty. defend your history.", cast: ['the_philosopher','the_historian','the_cynic','the_oracle'] },
  // ── lighter stakes ──
  { id: 'roast',      g: 'light', name: 'The Roast',        ic: '☄', tag: 'comedy', desc: "it's your roast. the table has receipts, the jokes are sharpened, and the only way out is through. take your hits, land yours back, and win the room by the last toast.", cast: ['the_comic','the_diva','the_wannabe','the_brother'] },
  { id: 'realityfin', g: 'light', name: 'The Final Rose... or Not', ic: '★', tag: 'reality tv', desc: "the reality-show finale, two alliances, one betrayal already in motion — yours or theirs. play the last council like the season depends on it, because it does.", cast: ['the_diva','the_wannabe','the_media_manager','the_comic'] },
  { id: 'critic',     g: 'light', name: 'The Table Nine',   ic: '♨', tag: 'the restaurant', desc: "the country's most feared food critic is at table nine, the sauce split at seven, and your head chef just walked out. it's your restaurant. save the review with charm, honesty, and one perfect dish.", cast: ['the_diva','the_cynic','the_comic'] },
  { id: 'awardscandal', g: 'light', name: 'The Envelope',   ic: '✪', tag: 'PR crisis', desc: "the wrong name was read, the clip is everywhere, and both winners are in your greenroom demanding statements. you're the show's fixer. write the next hour of the internet.", cast: ['the_media_manager','the_diva','the_comic','the_cynic'] },
];

export const PINNED = [
  { id: 'headlines', name: 'Ripped from the Headlines', ic: '⚡', tag: 'live · this week', desc: "the moderator pulls something from the world this week and builds a scene around it. fresh every time. (situations, not real named people.)", cast: ['the_leader_opp','the_orator','the_cynic','the_economist','the_media_manager'] },
  { id: 'surprise',  name: 'Surprise Me',               ic: '✨', tag: 'generated', desc: "the moderator invents a fresh scene from anywhere — any genre, any tone. you find out when you arrive.", cast: ['the_leader_opp','the_orator','the_cynic','the_brother'] },
  { id: 'custom',    name: 'Type Your Own',             ic: '✎', tag: 'yours', desc: "describe any scene you want — a heist, a trial, a finale you'd rewrite, a moment from history. the moderator builds it. every scene gets a mission.", cast: ['the_leader_opp','the_orator','the_cynic','the_brother'] },
];

export function shuffleFeatured(n = 6) {
  const a = LIBRARY.slice();
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a.slice(0, n);
}
export const byId = (id) => LIBRARY.concat(PINNED).find((s) => s.id === id);
export const KICKOFF = (id) =>
  id === 'custom' ? "let's begin — set the scene and tell me my options."
  : id === 'surprise' ? 'surprise me — invent something fresh, any genre, and set the scene.'
  : id === 'headlines' ? 'pull something from the world this week and build the scene — then set it up for me.'
  : 'begin the scene.';
